app:
  show: 5
  retrieve:
    top_k: 1000
    score_threshold: 0.2
    min_year: 1900
    rank_metric: log-mean
  style:
    imageWidth: 450
    logoUrl: https://medialab.sciencespo.fr/static/logo_medialab_d4a4a5af-92bb-4651-97e7-22272a5a5d3f.png
corpus:
  max_length: 1
  use_keys:
    abstract: true
    title: true
    subtitle: false
    keywords: false
  dump_file: hal-productions.json
  baseUrl: https://api.archives-ouvertes.fr
  portail: index
  query: 'labStructId_i:394361'
  pagination_count: 10000
  fields:
    - halId_s
    - uri_s
    - title_s
    - subtitle_s
    - abstract_s
    - publicationDate_s
    - citationFull_s
    - openAccess_bool
    - authIdHasPrimaryStructure_fs
    - authFullNameId_fs
    - keyword_s
    - docType_s
index:
  hnswlib_space: cosine
  ef_construction: 400
  M: 64
  num_threads: 1
  sentence_transformer_model: distiluse-base-multilingual-cased-v1
  sentence_transformer_model_dim: 512
  batch_size: 500
