app:
  style:
    logoUrl: https://medialab.sciencespo.fr/static/logo_medialab_d4a4a5af-92bb-4651-97e7-22272a5a5d3f.png
corpus:
  dump_file: hal-productions.json
  baseUrl: https://api.archives-ouvertes.fr
  labStructId_i: 394361
  collId_i: 9252
  pagination_count: 1000
  fields:
    - sciencespoId_s
    - halId_s
    - uri_s
    - docType_s
    - language_s
    - title_s
    - subtitle_s
    - abstract_s
    - description_s
    - en_title_s
    - en_subTitle_s
    - en_abstract_s
    - en_description_s
    - fr_title_s
    - fr_subTitle_s
    - fr_abstract_s
    - fr_description_s
    - modifiedDate_s
    - submittedDate_s
    - releasedDate_s
    - producedDate_s
    - publicationDate_s
    - ePublicationDate_s
    - conferenceStartDate_s
    - conferenceEndDate_s
    - writingDate_s
    - defenseDate_s
    - authFirstName_s
    - authLastName_s
    - citationFull_s
index:
    hnswlib_space: cosine
    sentence_transformer_model: distiluse-base-multilingual-cased-v1

