apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23-alpine
          imagePullPolicy: Always
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          env:
            - name: BACKEND_PORT
              value: '5000'
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: "default.conf"
                path: "default.conf"
