apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halexp-medialab-1phrase

bases:
  - ../../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

images:
  - name: scpomedialab/scpo-experts-search-nginx
    newTag: 'v0-4-0-beta'
  - name: scpomedialab/scpo-experts-search
    newTag: 'v0-4-0-beta'
