apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scpo-experts-search

namePrefix: scpo-experts-search-

bases:
  - ../../base/

resources:
  - ingress.yml

commonLabels:
  stage: development

images:
  - name: scpomedialab/scpo-experts-search
    newTag: 'main'
