apiVersion: apps/v1
kind: Deployment
metadata:
  name: halexp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: halexp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: halexp
    spec:
      containers:
        - name: halexp
          image: scpomedialab/scpo-experts-search:latest
          imagePullPolicy: Always
