apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halexp-medialab

bases:
  - ../../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

images:
  - name: scpomedialab/scpo-experts-search-nginx
    newTag: '0.8.0'
  - name: scpomedialab/scpo-experts-search
    newTag: '0.8.0'
