apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halexp-medialab

bases:
  - ../../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

images:
  - name: scpomedialab/scpo-experts-search-nginx
    newTag: 'v0-3-2-alpha'
  - name: scpomedialab/scpo-experts-search
    newTag: 'v0-3-2-alpha'
