apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halexp-medialab

namePrefix: halexp-medialab-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

images:
  - name: nginx
    newTag: '1.23-alpine'
  - name: scpomedialab/scpo-experts-search
    newTag: 'staging'
