apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - halexp/deployment.yml
  - halexp/service.yml
  - nginx/config-map.yml
  - nginx/deployment.yml
  - nginx/service.yml

commonLabels:
  owner: medialab
  name: scpo-experts-search
