apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halexp-sciencespo

bases:
  - ../../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: prod

images:
  - name: scpomedialab/scpo-experts-search-nginx
    newTag: '0.7.1'
  - name: scpomedialab/scpo-experts-search
    newTag: '0.7.1'
