apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: experts-search-pprd.sciencespo.fr
    http:
      paths:
        - path: /
          backend:
            serviceName: client
            servicePort: 80
